version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: python main.py
  test:
    steps:
      - checkout
      - run: python test.py
  deploy:
    steps:
      - run: echo "practical done"
  
  workflows:
    build_and_test_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: main 

